version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:8
      - image: circleci/postgres:9.6.2-alpine
    steps:
      - checkout
      - run:
          name: Setting up Database
          command: sudo -u postgres psql -p 5432 -c "DROP DATABASE IF EXISTS "gauntlet-development";"
          command: sudo -u postgres psql -p 5432 -c "CREATE DATABASE "gauntlet-development";"
      - run: npm install
      - run: npm test