version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:8
      - image: circleci/postgres:9.6.2-alpine
        environment:
          - POSTGRES_USER=ubuntu
          - POSTGRES_DB=gauntlet-development
    steps:
      - checkout
      - run: npm install
      - run: npm test