version: "2"
networks:
  myapp:

services:
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_DB: gauntlet-docker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      myapp:
        aliases:
          - postgres
  web:
    build: .
    command: [sh, -c, "npm run build && npm start"]
    ports:
      - "80:3000"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
    networks:
      myapp:
        aliases:
          - web